# Generated by Django 5.0 on 2024-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 8:55', '8:00 - 8:55'), ('8:55 - 9:50', '8:55 - 9:50'), ('10:10 - 11:05', '10:10 - 11:05'), ('11:05 - 12:00', '11:05 - 12:00'), ('10:10 - 12:00', '10:10 - 12:00'), ('1:00 - 1:50', '1:00 - 1:50'), ('2:10 - 3:05', '2:10 - 3:05'), ('3:05 - 4:00', '3:05 - 4:00'), ('2:10 - 4:00', '2:10 - 4:00'), ('4:10 - 5:05', '4:10 - 5:05'), ('5:05 - 6:00', '5:05 - 6:00')], default='11:00 - 12:00', max_length=50),
        ),
    ]
