# Generated by Django 5.0 on 2024-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0003_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 8:55', '8:00 - 8:55'), ('8:55 - 9:50', '8:55 - 9:50'), ('3:05 - 4:00', '3:05 - 4:00'), ('2:10 - 4:00', '2:10 - 4:00'), ('4:10 - 5:05', '4:10 - 5:05'), ('5:05 - 6:00', '5:05 - 6:00')], default='11:00 - 12:00', max_length=50),
        ),
    ]
